export const C = {
  bg:      '#0d0d0f',
  panel:   '#131317',
  border:  '#222228',
  red:     '#cc2222',
  purple:  '#7c5cff',
  text:    '#d4d4d8',
  muted:   '#71717a',
  white:   '#f4f4f5',
  orange:  '#ff6b35',
  amber:   '#f59e0b',
  green:   '#22c55e',
};

export const S = {
  page: {
    background: C.bg,
    minHeight: '100vh',
    color: C.text,
    fontFamily: 'Tahoma, Verdana, sans-serif',
    fontSize: '13px',
  } as React.CSSProperties,
  panel: {
    background: C.panel,
    border: `1px solid ${C.border}`,
  } as React.CSSProperties,
  input: {
    width: '100%',
    background: C.bg,
    border: `1px solid ${C.border}`,
    color: C.text,
    padding: '6px 8px',
    fontSize: '13px',
    fontFamily: 'Tahoma, Verdana, sans-serif',
    outline: 'none',
  } as React.CSSProperties,
  btn: {
    background: C.red,
    color: C.white,
    border: 'none',
    padding: '5px 14px',
    fontSize: '12px',
    cursor: 'pointer',
    fontWeight: 'bold',
    borderRadius: '2px',
    fontFamily: 'Tahoma, Verdana, sans-serif',
  } as React.CSSProperties,
  btnSecondary: {
    background: 'transparent',
    color: C.muted,
    border: `1px solid ${C.border}`,
    padding: '5px 14px',
    fontSize: '12px',
    cursor: 'pointer',
    borderRadius: '2px',
    fontFamily: 'Tahoma, Verdana, sans-serif',
  } as React.CSSProperties,
  sectionHead: {
    background: '#1a1a20',
    borderBottom: `1px solid ${C.border}`,
    padding: '6px 10px',
    fontFamily: 'Impact, Arial Black, sans-serif',
    fontSize: '12px',
    letterSpacing: '1px',
    color: C.white,
    textTransform: 'uppercase' as const,
  },
};
